/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 -t public/models/wille.glb --transform 
Files: public/models/wille.glb [786.65KB] > C:\Backend\Nextjs\writeups.zer0cheros.fi\wille-transformed.glb [95.69KB] (88%)
Author: tramdrey (https://sketchfab.com/tramdrey)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/steamboat-willie-58c5716c49c947f2a5aa152cec39cec0
Title: Steamboat Willie
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_White_0: THREE.Mesh
    Cylinder_Outline_0: THREE.Mesh
    Torus001_Textures_0: THREE.Mesh
  }
  materials: {
    White: THREE.MeshBasicMaterial
    Outline: THREE.MeshBasicMaterial
    Textures: THREE.MeshBasicMaterial
  }
  
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/wille-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_White_0.geometry} material={materials.White} position={[3.268, 1.48, 0.004]} rotation={[-1.638, 0, -0.668]} />
      <mesh geometry={nodes.Cylinder_Outline_0.geometry} material={materials.Outline} position={[3.268, 1.48, 0.004]} rotation={[-1.638, 0, -0.668]} />
      <mesh geometry={nodes.Torus001_Textures_0.geometry} material={materials.Textures} position={[4.38, 0.343, -0.172]} rotation={[-Math.PI / 2, 0, 0.442]} />
    </group>
  )
}

useGLTF.preload('models/wille-transformed.glb')
